
server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost:3306/studentsys
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sqluser
    password: password